# -*- coding: utf-8 -*-
from PIL import Image, ImageFilter
from histogram_filter import generate_histogram

# Form implementation generated from reading ui file '/Users/weam/Desktop/histogramDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QFileDialog, QGraphicsScene, QGraphicsPixmapItem

from histogram_filter import generate_histogram


class Ui_histogramDesign(object):
    def setupUi(self, histogramDesign):
        histogramDesign.setObjectName("histogramDesign")
        histogramDesign.resize(1073, 658)
        self.centralwidget = QtWidgets.QWidget(histogramDesign)
        self.centralwidget.setObjectName("centralwidget")
        self.btnUplead = QtWidgets.QPushButton(self.centralwidget)
        self.btnUplead.setGeometry(QtCore.QRect(750, 450, 110, 32))
        self.btnUplead.setObjectName("btnUplead")
        self.graphicsView2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView2.setGeometry(QtCore.QRect(60, 20, 471, 411))
        self.graphicsView2.setObjectName("graphicsView2")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(230, 450, 110, 32))
        self.btnSave.setObjectName("btnSave")
        self.graphicsView1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView1.setGeometry(QtCore.QRect(560, 20, 471, 411))
        self.graphicsView1.setObjectName("graphicsView1")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(500, 540, 110, 32))
        self.btnApply.setObjectName("btnApply")

        self.max_pixel_count_label = QtWidgets.QLabel(self.centralwidget)
        self.max_pixel_count_label.setGeometry(QtCore.QRect(510, 470, 160, 16))
        self.max_pixel_count_label.setObjectName("label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, 500, 160, 21))
        self.label.setObjectName("lineEdit")
        histogramDesign.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(histogramDesign)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1073, 24))
        self.menubar.setObjectName("menubar")
        histogramDesign.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(histogramDesign)
        self.statusbar.setObjectName("statusbar")
        histogramDesign.setStatusBar(self.statusbar)

        self.retranslateUi(histogramDesign)
        QtCore.QMetaObject.connectSlotsByName(histogramDesign)

    def load_image(self, event):
         options = QFileDialog.Options()
         options |= QFileDialog.DontUseNativeDialog
         file_name, _ = QFileDialog.getOpenFileName(None, "Choose Image", "", "Images (*.png *.jpg *.bmp *.gif);;All Files (*)", options=options)
         file_dialog = QFileDialog()
         file_dialog.setDirectory('/Users/weam')

         if file_name:
            self.image_path = file_name
            pixmap = QtGui.QPixmap(self.image_path)

            scene = QGraphicsScene()
            item = QGraphicsPixmapItem(pixmap)

            # Scale the image to fit within the graphics view's viewport
            item.setScale(min(self.graphicsView1.viewport().width() / pixmap.width(),
                           self.graphicsView1.viewport().height() / pixmap.height()))

            scene.addItem(item)
            self.graphicsView1.setScene(scene)



    def __init__(self):
        # Create pen objects
        self.penRed = QtGui.QPen(QtCore.Qt.red)  # Create a red pen
        self.penBlack = QtGui.QPen(QtCore.Qt.black)  # Create a black pen


    def apply_histogram(self):

     if self.image_path:
            original_image = Image.open(self.image_path).convert("RGBA")

            if self.graphicsView2.scene() is None:
                self.graphicsView2.setScene(QGraphicsScene())

            generate_histogram(original_image, self.graphicsView2.scene(), self.label, self.max_pixel_count_label, self.penRed)


    def retranslateUi(self, histogramDesign):
        _translate = QtCore.QCoreApplication.translate
        histogramDesign.setWindowTitle(_translate("histogramDesign", "MainWindow"))
        self.btnUplead.setText(_translate("histogramDesign", "Upload image"))
        self.btnUplead.clicked.connect(self.load_image)

        self.btnSave.setText(_translate("histogramDesign", "Save image"))
        self.btnApply.setText(_translate("histogramDesign", "Apply filter"))
        self.btnApply.clicked.connect(self.apply_histogram)
        self.max_pixel_count_label.setText(_translate("histogramDesign", " "))
        self.label.setText(_translate("histogramDesign", " "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    histogramDesign = QtWidgets.QMainWindow()
    ui = Ui_histogramDesign()
    ui.setupUi(histogramDesign)
    histogramDesign.show()
    sys.exit(app.exec_())
