# -*- coding: utf-8 -*-
import numpy as np
from PIL import Image
# Form implementation generated from reading ui file '/Users/weam/Desktop/perspectiveDesign222.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QGraphicsScene, QGraphicsPixmapItem

from perspective_filter import perspective_correction


class Ui_perspectiveDesign(object):
    def setupUi(self, perspectiveDesign):
        perspectiveDesign.setObjectName("perspectiveDesign")
        perspectiveDesign.resize(1011, 660)

        self.src_points = []
        self.dst_points = []

        self.is_selecting_src = True


        self.centralwidget = QtWidgets.QWidget(perspectiveDesign)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView2.setGeometry(QtCore.QRect(20, 0, 471, 411))
        self.graphicsView2.setObjectName("graphicsView2")
        self.graphicsView1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView1.setGeometry(QtCore.QRect(520, 0, 471, 411))
        self.graphicsView1.setObjectName("graphicsView1")
        self.btnUpload = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpload.setGeometry(QtCore.QRect(710, 430, 110, 32))
        self.btnUpload.setObjectName("btnUpload")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(190, 430, 110, 32))
        self.btnSave.setObjectName("btnSavep")
        self.btnReset = QtWidgets.QPushButton(self.centralwidget)
        self.btnReset.setGeometry(QtCore.QRect(450, 500, 110, 32))
        self.btnReset.setObjectName("btnReset")
        self.txtSxy1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSxy1.setGeometry(QtCore.QRect(140, 500, 90, 21))
        self.txtSxy1.setObjectName("txtSxy1")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(450, 540, 110, 32))
        self.btnApply.setObjectName("btnApply")
        self.labelsxy1 = QtWidgets.QLabel(self.centralwidget)
        self.labelsxy1.setGeometry(QtCore.QRect(80, 500, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.labelsxy1.setFont(font)
        self.labelsxy1.setLineWidth(1)
        self.labelsxy1.setObjectName("labelsxy1")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(150, 570, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setLineWidth(1)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(720, 560, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setLineWidth(1)
        self.label_18.setObjectName("label_18")
        self.txtSxy2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSxy2.setGeometry(QtCore.QRect(140, 540, 90, 21))
        self.txtSxy2.setText("")
        self.txtSxy2.setObjectName("txtSxy2")
        self.labelsxy2 = QtWidgets.QLabel(self.centralwidget)
        self.labelsxy2.setGeometry(QtCore.QRect(80, 540, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.labelsxy2.setFont(font)
        self.labelsxy2.setLineWidth(1)
        self.labelsxy2.setObjectName("labelsxy2")
        self.txtSxy4 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSxy4.setGeometry(QtCore.QRect(300, 540, 90, 21))
        self.txtSxy4.setText("")
        self.txtSxy4.setObjectName("txtSxy4")
        self.txtSxy3 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSxy3.setGeometry(QtCore.QRect(300, 500, 90, 21))
        self.txtSxy3.setObjectName("txtSxy3")
        self.labelsxy4 = QtWidgets.QLabel(self.centralwidget)
        self.labelsxy4.setGeometry(QtCore.QRect(240, 540, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.labelsxy4.setFont(font)
        self.labelsxy4.setLineWidth(1)
        self.labelsxy4.setObjectName("labelsxy4")
        self.labelsxy3 = QtWidgets.QLabel(self.centralwidget)
        self.labelsxy3.setGeometry(QtCore.QRect(240, 500, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.labelsxy3.setFont(font)
        self.labelsxy3.setLineWidth(1)
        self.labelsxy3.setObjectName("labelsxy3")
        self.txtDxy4 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtDxy4.setGeometry(QtCore.QRect(830, 530, 90, 21))
        self.txtDxy4.setText("")
        self.txtDxy4.setObjectName("txtDxy4")
        self.txtDxy3 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtDxy3.setGeometry(QtCore.QRect(830, 490, 90, 21))
        self.txtDxy3.setObjectName("txtDxy3")
        self.labelDxy2 = QtWidgets.QLabel(self.centralwidget)
        self.labelDxy2.setGeometry(QtCore.QRect(610, 530, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.labelDxy2.setFont(font)
        self.labelDxy2.setLineWidth(1)
        self.labelDxy2.setObjectName("labelDxy2")
        self.labelDxy1 = QtWidgets.QLabel(self.centralwidget)
        self.labelDxy1.setGeometry(QtCore.QRect(610, 490, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.labelDxy1.setFont(font)
        self.labelDxy1.setLineWidth(1)
        self.labelDxy1.setObjectName("labelDxy1")
        self.txtDxy2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtDxy2.setGeometry(QtCore.QRect(670, 530, 90, 21))
        self.txtDxy2.setText("")
        self.txtDxy2.setObjectName("txtDxy2")
        self.labelDxy4 = QtWidgets.QLabel(self.centralwidget)
        self.labelDxy4.setGeometry(QtCore.QRect(770, 530, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.labelDxy4.setFont(font)
        self.labelDxy4.setLineWidth(1)
        self.labelDxy4.setObjectName("labelDxy4")
        self.labelDxy3 = QtWidgets.QLabel(self.centralwidget)
        self.labelDxy3.setGeometry(QtCore.QRect(770, 490, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.labelDxy3.setFont(font)
        self.labelDxy3.setLineWidth(1)
        self.labelDxy3.setObjectName("labelDxy3")
        self.txtDxy1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtDxy1.setGeometry(QtCore.QRect(670, 490, 90, 21))
        self.txtDxy1.setObjectName("txtDxy1")
        perspectiveDesign.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(perspectiveDesign)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1011, 24))
        self.menubar.setObjectName("menubar")
        perspectiveDesign.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(perspectiveDesign)
        self.statusbar.setObjectName("statusbar")
        perspectiveDesign.setStatusBar(self.statusbar)

        self.graphicsView1.mousePressEvent = self.select_points
        self.all_src_points = []
        self.all_dst_points = []

        self.current_selection = "source"
        self.graphicsView1.click_handler = self.select_points


        self.retranslateUi(perspectiveDesign)
        QtCore.QMetaObject.connectSlotsByName(perspectiveDesign)



    def load_image(self, event):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        file_name, _ = QFileDialog.getOpenFileName(None, "Choose Image", "", "Images (*.png *.jpg *.bmp *.gif);;All Files (*)", options=options)
        file_dialog = QFileDialog()
        file_dialog.setDirectory('/Users/weam')

        if file_name:
           self.image_path = file_name
           pixmap = QtGui.QPixmap(self.image_path)


           scene = QGraphicsScene()


           item = QGraphicsPixmapItem(pixmap)


           item.setScale(min(self.graphicsView1.viewport().width() / pixmap.width(),
                       self.graphicsView1.viewport().height() / pixmap.height()))

           scene.addItem(item)
           self.graphicsView1.setScene(scene)


    def select_points(self, event):

        pos = self.graphicsView1.mapToScene(event.pos())
        x, y = pos.x(), pos.y()


        if self.current_selection == "source":
            self.src_points.append((x, y))
            self.all_src_points.append((x, y))
            self.update_src_point_text()
            self.current_selection = "destination"
        else:
            self.dst_points.append((x, y))
            self.all_dst_points.append((x, y))  # تحديث المتغير الجديد
            self.update_dst_point_text()
            self.current_selection = "source"


    def update_src_point_text(self):
    # Update source point text fields based on the number of selected points
        points = self.src_points[-1]
        if len(self.src_points) == 1:
           self.txtSxy1.setText(f"{points[0]:.2f}, {points[1]:.2f}")
        elif len(self.src_points) == 2:
           self.txtSxy2.setText(f"{points[0]:.2f}, {points[1]:.2f}")
        elif len(self.src_points) == 3:
           self.txtSxy3.setText(f"{points[0]:.2f}, {points[1]:.2f}")
        elif len(self.src_points) == 4:
           self.txtSxy4.setText(f"{points[0]:.2f}, {points[1]:.2f}")

    def update_dst_point_text(self):
    # Update destination point text fields based on the number of selected points
        points = self.dst_points[-1]
        if len(self.dst_points) == 1:
           self.txtDxy1.setText(f"{points[0]:.2f}, {points[1]:.2f}")
        elif len(self.dst_points) == 2:
           self.txtDxy2.setText(f"{points[0]:.2f}, {points[1]:.2f}")
        elif len(self.dst_points) == 3:
           self.txtDxy3.setText(f"{points[0]:.2f}, {points[1]:.2f}")
        elif len(self.dst_points) == 4:
           self.txtDxy4.setText(f"{points[0]:.2f}, {points[1]:.2f}")

    def apply_perspective_correction(self):
      if all(field.text() for field in [self.txtSxy1, self.txtSxy2, self.txtSxy3, self.txtSxy4, self.txtDxy1, self.txtDxy2, self.txtDxy3, self.txtDxy4]):

        src_points = np.array(self.all_src_points)
        dst_points = np.array(self.all_dst_points)

        original_image = Image.open(self.image_path)

        corrected_image = perspective_correction(src_points, dst_points, original_image)

        if len(self.all_src_points) != 4 or len(self.all_dst_points) != 4:
         print("Error: Please select exactly 4 source and 4 destination points.")
        return
        print("Source Points:", self.all_src_points)
        print("Destination Points:", self.all_dst_points)
        print("Shapes:", np.shape(self.all_src_points), np.shape(self.all_dst_points))


        print("Source Points:", src_points)
        print("Destination Points:", dst_points)

        pixmap = QtGui.QPixmap.fromImage(QtGui.QImage(corrected_image.tobytes(), corrected_image.size[0], corrected_image.size[1], QtGui.QImage.Format_RGB888))
        scene = QtWidgets.QGraphicsScene()
        item = QtWidgets.QGraphicsPixmapItem(pixmap)
        scene.addItem(item)
        self.graphicsView2.setScene(scene)



    def reset_points(self):
        self.src_points = []
        self.dst_points = []

        self.txtSxy1.setText("")
        self.txtSxy2.setText("")
        self.txtSxy3.setText("")
        self.txtSxy4.setText("")
        self.txtDxy1.setText("")
        self.txtDxy2.setText("")
        self.txtDxy3.setText("")
        self.txtDxy4.setText("")

        self.is_selecting_src = True

        scene = self.graphicsView2.scene()
        if scene:
            for item in scene.items():
                scene.removeItem(item)




    def retranslateUi(self, perspectiveDesign):
        _translate = QtCore.QCoreApplication.translate
        perspectiveDesign.setWindowTitle(_translate("perspectiveDesign", "MainWindow"))

        self.btnUpload.clicked.connect(self.load_image)
        self.btnApply.clicked.connect(self.apply_perspective_correction)

        self.graphicsView1.mousePressEvent = self.select_points

        self.btnUpload.setText(_translate("perspectiveDesign", "Upload image"))
        self.btnSave.setText(_translate("perspectiveDesign", "Save image"))
        self.btnApply.setText(_translate("perspectiveDesign", "Apply filter"))
        self.btnReset.setText(_translate("perspectiveDesign", "Reset"))
        self.btnReset.clicked.connect(self.reset_points)

        self.labelsxy1.setText(_translate("perspectiveDesign", "X1, Y1:"))
        self.label_17.setText(_translate("perspectiveDesign", "Source Point"))
        self.label_18.setText(_translate("perspectiveDesign", "Destination Point"))
        self.labelsxy2.setText(_translate("perspectiveDesign", "X2, Y2:"))
        self.labelsxy4.setText(_translate("perspectiveDesign", "X4, Y4:"))
        self.labelsxy3.setText(_translate("perspectiveDesign", "X3, Y3:"))
        self.labelDxy2.setText(_translate("perspectiveDesign", "X2, Y2:"))
        self.labelDxy1.setText(_translate("perspectiveDesign", "X1, Y1:"))
        self.labelDxy4.setText(_translate("perspectiveDesign", "X4, Y4:"))
        self.labelDxy3.setText(_translate("perspectiveDesign", "X3, Y3:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    perspectiveDesign = QtWidgets.QMainWindow()
    ui = Ui_perspectiveDesign()
    ui.setupUi(perspectiveDesign)
    perspectiveDesign.show()
    sys.exit(app.exec_())
